sessionLifetime : 3600
team : 9
numberTeams : 2
webPassword : "password"
apiToken : "token"
teamFormat : "10.60.x.1"
wildcard : "x"
teamIP : "10.60.1.1"
clientPort : 5050
nopTeam : "10.60.0.1"
roundDuration : 120
flagFormat : "[A-Z0-9]{31}="
flagIDurl : ""
subProtocol : "ccit"
subLimit : 1
subInterval : 20
subPayloadSize : 500
subUrl : "http://localhost:8000/flags"
dbnsub : "NOT_SUBMITTED"
dbsub : "SUBMITTED"
dbsucc : "SUCCESS"
dberr : "ERROR"
dbexp : "EXPIRED"
database : "instance/flagSubmitter.sqlite"