serverConf:
  sessionLifetime : 3600
  database : "instance/flagSubmitter.sqlite"
  clientPort : 5050
  apiToken : "token"
gameConf:
  numberTeams : 10
  teamFormat : "10.60.x.1"
  wildcard : "x"
  teamIP : "10.60.1.1"
  teamToken : "8a8d25f465bec01d"
  nopTeam : "10.60.0.1"
  roundDuration : 120
  flagFormat : "[A-Z0-9]{31}="
  flagIDurl : ""
  flagAlive : 5
submissionConf:
  subProtocol : "ccit"
  subLimit : 1
  subInterval : 20
  subPayloadSize : 500
  subUrl : "http://localhost:8000/flags"
  dbnsub : "NOT_SUBMITTED"
  dbsub : "SUBMITTED"
  dbsucc : "SUCCESS"
  dberr : "ERROR"
  dbexp : "EXPIRED"
authConf:
  webPassword : "password"
  authEnable: false
  users: [{"admin", "password"},{"hack3r", "mysecretpassword"}]
